import { describe, expect, test } from 'bun:test';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '../..');

describe('Phoenix scaffold', () => {
  test('pins the approved direct JavaScript dependencies', async () => {
    const pkg = await Bun.file(resolve(root, 'package.json')).json();
    expect(pkg.packageManager).toBe('bun@1.3.1');
    expect(pkg.dependencies).toEqual({ phaser: '4.2.1', svelte: '5.56.8' });
    expect(pkg.devDependencies).toEqual({
      '@eslint/js': '10.0.1',
      '@playwright/test': '1.62.1',
      '@sveltejs/vite-plugin-svelte': '7.3.0',
      '@tauri-apps/cli': '2.11.4',
      '@typescript/native': 'npm:typescript@7.0.2',
      '@types/bun': '1.3.14',
      eslint: '10.8.1',
      'eslint-config-prettier': '10.1.8',
      'eslint-plugin-svelte': '3.23.0',
      globals: '17.11.0',
      husky: '9.1.7',
      'lint-staged': '17.3.0',
      prettier: '3.9.6',
      'prettier-plugin-svelte': '4.1.1',
      'svelte-check': '4.7.5',
      typescript: '6.0.3',
      'typescript-eslint': '8.67.0',
      vite: '8.2.1',
    });
    expect(pkg.scripts).toMatchObject({
      check: 'svelte-check --tsconfig ./tsconfig.json --tsgo',
      lint: 'eslint .',
      'lint:fix': 'eslint . --fix',
      format: 'prettier --write .',
      'format:check': 'prettier --check .',
      prepare: 'husky',
      'test:coverage': 'bun test --coverage --coverage-reporter=lcov',
      'coverage:check': 'bun run tools/check-coverage.ts',
      'test:e2e:install:ci': 'playwright install --with-deps chromium',
    });
    expect(pkg['lint-staged']).toEqual({
      '*.{js,mjs,cjs,ts,svelte}': ['eslint --fix', 'prettier --write'],
      '*.{json,css,md,yml,yaml}': 'prettier --write',
    });
  });

  test('uses only Bun and Cargo lockfiles', () => {
    expect(existsSync(resolve(root, 'bun.lock'))).toBe(true);
    expect(existsSync(resolve(root, 'src-tauri/Cargo.lock'))).toBe(true);
    for (const forbidden of ['package-lock.json', 'pnpm-lock.yaml', 'yarn.lock']) {
      expect(existsSync(resolve(root, forbidden))).toBe(false);
    }
  });

  test('ignores caches generated by required quality and native checks', () => {
    for (const generated of [
      '.svelte-check/probe',
      'coverage/probe/lcov.info',
      'src-tauri/gen/schemas/probe.json',
    ]) {
      const result = Bun.spawnSync(['git', 'check-ignore', '--quiet', generated], { cwd: root });
      expect(result.exitCode).toBe(0);
    }
  });

  test('configures the requested formatting, linting, coverage, and staged hook boundaries', async () => {
    for (const path of [
      'eslint.config.js',
      '.prettierrc.json',
      '.prettierignore',
      'bunfig.toml',
      '.husky/pre-commit',
    ]) {
      expect(existsSync(resolve(root, path))).toBe(true);
    }

    const prettier = await Bun.file(resolve(root, '.prettierrc.json')).json();
    expect(prettier).toEqual({
      plugins: ['prettier-plugin-svelte'],
      printWidth: 100,
      singleQuote: true,
      trailingComma: 'all',
    });
    expect(await Bun.file(resolve(root, '.husky/pre-commit')).text()).toBe(
      '#!/usr/bin/env sh\nbunx lint-staged\n',
    );
  });

  test('configures the macOS-first Tauri window and Bun hooks', async () => {
    const config = await Bun.file(resolve(root, 'src-tauri/tauri.conf.json')).json();
    expect(config.identifier).toBe('com.hapadona.phoenix');
    expect(config.build).toEqual({
      beforeDevCommand: 'bun run dev',
      beforeBuildCommand: 'bun run build',
      devUrl: 'http://localhost:1420',
      frontendDist: '../dist',
    });
    expect(config.app.windows[0]).toMatchObject({
      label: 'main',
      title: 'Phoenix',
      width: 1280,
      height: 720,
      minWidth: 640,
      minHeight: 360,
    });
  });
});
